### PR TITLE
Spellcheck and en_US-ify

### PR DESCRIPTION
**Pull request by gladhorn**

### CODE REVIEW

**Comment by lydiapintscher** [comment]
I think trainings is correct here.

**Comment by gladhorn** [comment]
My understanding is that the plural of training is training. But I don't care much, feel free to change/abandon/amend as you see fit :) I just ran a spell checker on some texts.

**Comment by gladhorn** [comment]
@aleixpol feel free to decide :)

**Comment by aleixpol** [comment]
Thanks @gladhorn. I think it can be better. I'll just get it in.

**Pull request merged**
